# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除标记')),
                ('username', models.CharField(help_text='用户名', max_length=20)),
                ('password', models.CharField(help_text='密码', max_length=40)),
                ('email', models.EmailField(help_text='邮箱', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
