# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passport',
            table='s_user_account',
        ),
    ]
